ast: if
romildo/bcc328.2020.3 pull request #51
Opened 2020-09-06 19:46 UTC by kodagabriel

Bom dia! Implementei o analisador sintático para o IF. 
Estou ainda na dúvida sobre a implementação do if/else, mas posso fazer em outro PR!

2020-09-06 23:06 UTC, romildo requested changes

2020-09-06 23:06 UTC, romildo commented on src/lib/absyn.ml
> +  | IfExp     of (lexp * lexp)
É melhor colocar o else them. Vou explicar em outro comentário.

2020-09-06 23:06 UTC, romildo commented on src/lib/parser.mly
> +%token                 WHILE
Tira esses brancos que estão no final dessa linha do `WHILE`.

2020-09-06 23:19 UTC, romildo commented
# Representação da expressão condicional

- Basta acrescentar **um** novo construtor (`IfExp`) de dados em `exp`, mesmo quando uma parte da construção (`else`) é opcional.
- Vai precisar de três campos, um para cada componente da expressão condicional:
  - o teste
  - a primeira alternativa
  - a segunda alternativa (que é opcional)

# Como representar um valor opcional em OCaml

Use o tipo polimórfico `'a option`, da biblioteca padrão do OCaml. Veja o módulo [`Option`](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Option.html).

`'a option` é o tipo dos valores opcionais do tipo `'a`. Seus valores são de duas formas possíveis:
- `None`: é uma constante e representa a ausência de um valor
- `Some x`: é um estrutura com um campo para informar o valor presente (`x`, neste exemplo)

Exemplo:
``` ocaml
let v1 = None
let v2 = Some 798
let v3 = Some "coffee"
```

- `v1` é do tipo `'a option` e indica um valor opcional vazio.
- `v2` é do tipo `int option` e indica que um valor do tipo `int` está presente e este valor é `798`
- `v3` é do tipo `string option` e indica que um valor do tipo `string` está presente e este valor é `"coffee"`

2020-09-06 23:31 UTC, romildo commented
# Como fazer uma regra de produção para uma cadeia opcional

- O valor semântico será expresso como um valor opcional do OCaml.
- Pode-se usar duas regras de produção, uma para cada caso (cadeia ausente/cadeia presente).
- Exemplo:
  ```
  integer_opcional:
  |          { None }
  | x=LITINT { Some x }
  ```
- Em https://github.com/romildo/bcc328.2020.3/pull/49#issuecomment-687809480 foi explicado sobre a [biblioteca padrão do menhir](http://gallium.inria.fr/~fpottier/menhir/manual.html#sec%3Alibrary). Ela oferece o não terminal parametrizado `option` para esta situação.

- O exemplo acima usando este não terminal fica:
  ```
  integer_opcional: z=option(LITINT)  { z }
  ```

2020-09-07 19:59 UTC, kodagabriel commented
Bom dia.
No arquivo parser.mly minha alteração ficou assim
| IF t=exp THEN b=exp ELSE v=option(exp) {$loc, IfExp (t,b,v)}


Mas estou na duvida em como ficaria a representação do lexp opcional no arquivo absyn.ml e no absyntree.ml!
Como eu poderia fazer nesses casos?

2020-09-07 20:44 UTC, romildo commented
Você já tem no módulo `Absyn`:
``` ocaml
type exp = 
  (* ... *)
  | IfExp     of (lexp * lexp)
```
Então o construtor de dados `IfExp` declarado tem somente dois campos: do teste (condição), e da primeira alternativa (then). Falta você acrescentar um terceiro campo para a segunda alternativa (else), que é uma expressão opcional (do tipo `lexp option`).

2020-09-07 21:15 UTC, romildo commented
Na definição da função `Absyntree.tree_of_exp` você já tem a regra:
``` ocaml
let rec tree_of_exp exp =
  (* ... *)
  | IfExp (t,b)               -> mktr "IfExp" [tree_of_lexp t; tree_of_lexp b]
              ^^^                                                            ^^^
```
Por causa do terceiro campo que você vai ter adicionado (alternativa do else), você vai precisar:
- colocar mais um sub-padrão na estrutura da expressão if, que vai casar com a alternativa do else
- colocar mais um elemento na lista das sub-árvores (segundo argumento de `mktr`), para incluir a sub-árvore do componente correspondente ao else da estrutura do if; como ele é opcional (do tipo ( `lexp option`), você pode usar a função auxiliar `tree_of_option`que foi explicada em https://github.com/romildo/bcc328.2020.3/pull/55#issuecomment-688274786

Eis a implementação da função `Absyntree.tree_of_option`:
``` ocaml
let tree_of_option f = function
  | None -> Tree.empty
  | Some x -> f x
```

Ela depende de uma versão atualizada do módulo `Tree`, colocada hoje no branch `master`

2020-09-08 00:39 UTC, kodagabriel commented
Fiz aqui, e agora funciona com o if/then/else e com o if/then apenas também funciona mas imprime assim. É assim mesmo? 
![image](https://user-images.githubusercontent.com/35259369/92422166-99502480-f152-11ea-8690-75a4809fd235.png)

2020-09-08 01:34 UTC, romildo commented
> Fiz aqui, e agora funciona com o if/then/else e com o if/then apenas também funciona mas imprime assim. É assim mesmo?
> ![image](https://user-images.githubusercontent.com/35259369/92422166-99502480-f152-11ea-8690-75a4809fd235.png)

Sim. Fica evidente na árvore sintática que o else não está presente.

2020-09-08 01:40 UTC, romildo requested changes

2020-09-08 01:40 UTC, romildo commented on src/lib/parser.mly
> +| IF t=exp THEN b=exp option(ELSE) v=option(exp) {$loc, IfExp (t,b,v)}
Aqui você está colocando que o `ELSE` é opcional, **E/OU** a última  `exp` é opcional, pois você usou o não-terminal `option` duas vezes, independentemente uma da outra.

Tem que usar um único `option`, pois é a cadeia toda `ELSE exp` que é opcional:

```
v=option(ELSE c=exp {c})
```

2020-09-08 12:12 UTC, romildo commented
Agora falta corrigir esta regra de produção, como comentei anteriormente.
```
| IF t=exp THEN b=exp option(ELSE) v=option(exp) {$loc, IfExp (t,b,v)}
```

2020-09-08 12:23 UTC, kodagabriel commented
Sim, estava tentando resolver conflitos primeiro... Resolvi essa parte que você disse localmente mas após fazer pull da master e fazer rebase ele está dando erro em uma parte de outra pessoa... Não estou conseguindo testar. Na master está ok... Vou fazer um push e outro pull/rebase pra ver se resolve
![image](https://user-images.githubusercontent.com/35259369/92475722-3becbf80-f1b4-11ea-83cd-b8f4eb8dd2a3.png)

2020-09-08 12:39 UTC, kodagabriel commented
Tentei aqui e continua com esse erro :/ Não sei o que pode ser

2020-09-08 12:44 UTC, romildo commented
Vou ajudá-la a reorganizar o seu branch `kodagabriel:syntax_tree/if`.

- Vou fazer uma cópia local dele, tentar organizar, e fazer upload novamente.

Daqui a pouco retorno com instruções.

2020-09-08 12:44 UTC, closed without merging

2020-09-08 12:46 UTC, kodagabriel commented
Como são poucas mudanças, eu posso criar outra branch a partir da master e fazer de novo. Acredito ser mais fácil

2020-09-08 12:56 UTC, romildo commented
> Como são poucas mudanças, eu posso criar outra branch a partir da master e fazer de novo. Acredito ser mais fácil

Beleza!