Simplevar, letexp and vardec
romildo/bcc328.2020.3 pull request #55
Opened 2020-09-07 07:54 UTC by whitesimian

Apliquei, pelo que eu entendi, as mudanças e acrescentei as expressões _let_ que foi sugerido.

2020-09-07 11:04 UTC, romildo commented
Parece que está ok.

@whitesimian Você poderia mostrar alguns resultados da análise de expressões `let` e variáveis simples, como foi feito para operadores em https://github.com/romildo/bcc328.2020.3/pull/53#issuecomment-688001809?

2020-09-07 11:24 UTC, whitesimian commented
![image](https://user-images.githubusercontent.com/38870713/92382226-06c86a80-f0eb-11ea-9bba-73bed06a2ad5.png)
![image](https://user-images.githubusercontent.com/38870713/92382292-21024880-f0eb-11ea-87cd-f0b73a05f514.png)
![image](https://user-images.githubusercontent.com/38870713/92382587-966e1900-f0eb-11ea-9ba3-62999659060b.png)

As declarações nesta última imagem têm que estar separadas por vírgula?

2020-09-07 11:27 UTC, romildo commented
> As declarações nesta última imagem têm que estar separadas por vírgula?

Não. A linguagem não usa nenhum separador entre as declarações em uma lista de declarações. Mas repare que cada declaração de variável começa com a palavra-chave `var`.

2020-09-07 11:33 UTC, romildo requested changes

2020-09-07 11:33 UTC, romildo commented on src/lib/absyntree.ml
> +                                                                          tree_of_lexp z])
Eu tenho uma sugestão para melhorar a construção da árvore para componentes opcionais. Vai ser útil porque construções opcionais vai aparecer mais vezes no projeto. Vou explicar em outro comentário.

2020-09-07 11:50 UTC, romildo commented
## Convertendo um valor opcional para árvore genérica

- Como construções opcionais vai aparecer mais vezes nos tipos das árvores sintáticas, podemos generalizar algumas coisas.

- Defina no módulo `Absyntree` uma função
  ``` ocaml
  tree_of_option f opt
  ```
  que recebe:
  - uma função capaz de converter um valor para árvore genérica
  - um valor opcional
  e analisa a estrutura opcional:
  - se for vazia, retorna uma árvore genérica vazia
  - caso contrário, retorna uma árvore genérica  construída pela aplicação da função dada ao componente opcional

- Observe que os tipos do valor encapsulado e do parâmetro da função dada devem ser compatíveis.

- Por exemplo:
  ```
  tree_of_option tree_of_exp (Some (IntExp 17))
  ```

- Use essa função em `tree_of_exp` para o caso da declaração de variável, onde o tipo da variável é opcional.

2020-09-08 11:42 UTC, romildo approved these changes

2020-09-08 11:58 UTC, romildo commented
Resolvi os conflitos e fiz alguns pequenos ajustes no código.

Obrigado.

2020-09-08 12:00 UTC, merged